# Generated by Django 3.0.1 on 2020-01-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('length', models.CharField(max_length=6)),
            ],
        ),
    ]
